// js/glossary.js — plain-language definitions, shown as tooltips on the
// first use of each term in a page's prose (see ui.js prose()).
export const GLOSSARY = {
  token: 'A piece of text the model works with: often a word, sometimes part of a word, occasionally a single character.',
  tokens: 'Pieces of text the model works with: often words, sometimes parts of words, occasionally single characters.',
  tokenizer: 'The fixed recipe that cuts text into tokens, learned by repeatedly gluing the most common neighbouring pair.',
  dictionary: 'The list of every token the model can produce, each with a number.',
  vocabulary: 'The list of every token the model can produce, each with a number.',
  embedding: 'A token’s row of numbers — its “location”. Learned, so tokens that behave alike end up near each other.',
  embeddings: 'Each token’s row of numbers — its “location”. Learned, so tokens that behave alike end up near each other.',
  weight: 'Any number the model is allowed to change while learning. All the tables in this book are weights.',
  weights: 'The numbers the model is allowed to change while learning. All the tables in this book are weights.',
  parameter: 'Another word for a weight: a number the model adjusts while learning. This book has a few hundred; a chatbot has billions.',
  parameters: 'Another word for weights: the numbers the model adjusts while learning. This book has a few hundred; a chatbot has billions.',
  attention: 'The step where each token scores every other token and takes a weighted blend of their information.',
  query: 'In the attention analogy, a token’s question.',
  key: 'In the attention analogy, a token’s name badge.',
  value: 'In the attention analogy, the note a token hands over.',
  softmax: 'Turns any list of scores into shares that add up to 100%. Bigger scores get disproportionately bigger shares.',
  'residual connection': 'Adding a stage’s result onto its input, so the original is kept and the stage only proposes a change.',
  'layer normalisation': 'Rescaling a row of numbers so its average is 0 and its spread is 1.',
  'feed-forward': 'The small “think alone” network applied to each token separately.',
  bias: 'A fixed nudge added to every result of a multiplication.',
  'hidden unit': 'One column of the feed-forward block’s expanded table: a little detector that either fires or stays at 0.',
  logit: 'A raw score for one candidate token, before softmax turns it into a probability.',
  logits: 'The raw scores for every candidate token, before softmax turns them into probabilities.',
  surprise: 'How unlikely the model thought the real next token was (−log of the probability it gave). Training pushes it down.',
  loss: 'The number training tries to push down; here, the average surprise over the text.',
  'learning rate': 'How big a step each weight takes in one training round.',
  gradient: 'For each weight, which way and how much surprise changes if that weight is nudged — the direction training moves it.',
  backpropagation: 'The trick that computes every weight’s gradient in one pass backwards through the stages.',
  temperature: 'How much randomness to add when picking the next token: 0 always takes the favourite.',
  inference: 'Using a trained model with its weights frozen. Typing at a chatbot is inference; it teaches the model nothing.',
  training: 'Adjusting the weights, step by step, to make the model less surprised by real text.',
  'context window': 'The maximum number of tokens a model can look at at once. Here, 2,000.',
  'dot product': 'Multiply two rows number by number and add up: one number that is big when the rows agree.',
};
